services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - "5000"
    depends_on:
      - mail
    environment:
      - FLASK_ENV=production
      - MAIL_SERVER=mail
      - MAIL_PORT=1025

  mail:
    build: ./mail
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      - MAIL_SERVER=localhost
      - MAIL_PORT=1025

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  pycache:
    driver: local
