"""changed joining table between users and classes named user_subjects

Revision ID: 036612e7b35b
Revises: 8ba11dd983ff
Create Date: 2025-03-14 19:06:52.902919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036612e7b35b'
down_revision = '8ba11dd983ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subject',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_subjects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subjects',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('subject_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('user_subject')
    # ### end Alembic commands ###
