"""added workexamples table

Revision ID: 1e669aefdfc7
Revises: 8d9612932591
Create Date: 2025-05-07 23:46:27.810749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e669aefdfc7'
down_revision = '8d9612932591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_work_example_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_example'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_example')
    # ### end Alembic commands ###
