"""added review stuff

Revision ID: 43af2e35dae6
Revises: 85815701b053
Create Date: 2025-04-23 18:54:27.373468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43af2e35dae6'
down_revision = '85815701b053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_review_tutor_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_review_student_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_review_recipient_id_user'), 'user', ['recipient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_review_author_id_user'), 'user', ['author_id'], ['id'])
        batch_op.drop_column('student_id')
        batch_op.drop_column('tutor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tutor_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('student_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_review_author_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_review_recipient_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_review_student_id_user', 'user', ['student_id'], ['id'])
        batch_op.create_foreign_key('fk_review_tutor_id_user', 'user', ['tutor_id'], ['id'])
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
