"""reason for database change

Revision ID: 4eab757ee1ee
Revises: 8cf67d1eefaf
Create Date: 2025-04-02 16:04:03.094458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eab757ee1ee'
down_revision = '8cf67d1eefaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requested_subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_requested_subject_student_id_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_requested_subject_subject_id_subject')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requested_subject'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requested_subject')
    # ### end Alembic commands ###
