"""changed work examples relationship

Revision ID: 512335e477aa
Revises: bfcc384e91fb
Create Date: 2025-05-09 16:22:56.457486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512335e477aa'
down_revision = 'bfcc384e91fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_work_example_subject_id')
        batch_op.drop_index('ix_work_example_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.create_index('ix_work_example_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_work_example_subject_id', ['subject_id'], unique=False)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
