"""initial commit

Revision ID: 51783e8cd374
Revises: 85715930d790
Create Date: 2025-04-14 18:33:25.936235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51783e8cd374'
down_revision = '85715930d790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.alter_column('subject',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=140),
               existing_nullable=False)
        batch_op.drop_index('ix_alert_subject')
        batch_op.drop_constraint('fk_alert_subject_user', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_alert_subject_user', 'user', ['subject'], ['id'])
        batch_op.create_index('ix_alert_subject', ['subject'], unique=False)
        batch_op.alter_column('subject',
               existing_type=sa.String(length=140),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
