"""added availability model

Revision ID: 73132eb7b1a2
Revises: ffb09534e3f3
Create Date: 2025-04-15 16:15:49.520638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73132eb7b1a2'
down_revision = 'ffb09534e3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], name=op.f('fk_availability_tutor_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    # ### end Alembic commands ###
