"""add availability table

Revision ID: 823d65329aa6
Revises: a789749f0f61
Create Date: 2025-04-10 01:19:27.690369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823d65329aa6'
down_revision = 'a789749f0f61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tutor_id'], ['user.id'], name=op.f('fk_availability_tutor_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability')
    # ### end Alembic commands ###
