"""changed formatting of Appointment times

Revision ID: 84e9926753e5
Revises: 6da82a590020
Create Date: 2025-04-16 17:06:01.943478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e9926753e5'
down_revision = '6da82a590020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointment_created_date'), ['created_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_created_date'))

    # ### end Alembic commands ###
