"""added new column to other table

Revision ID: 9667139a2ff8
Revises: eeb9caaf8d09
Create Date: 2025-05-13 03:13:41.984686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9667139a2ff8'
down_revision = 'eeb9caaf8d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_other', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.drop_column('subject_other')

    # ### end Alembic commands ###
