"""changed appointment model

Revision ID: 9f6403afdf5e
Revises: 6d67eb5cab5a
Create Date: 2025-04-11 15:53:16.850964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6403afdf5e'
down_revision = '6d67eb5cab5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_date', sa.Date(), nullable=False))
        batch_op.alter_column('created_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_appointment_booking_time'), ['booking_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointment_booking_time'))
        batch_op.alter_column('created_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('booking_date')

    # ### end Alembic commands ###
