"""added alert relationships

Revision ID: a38fec28b2b8
Revises: 41ee1164e017
Create Date: 2025-04-19 21:30:55.231531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a38fec28b2b8'
down_revision = '41ee1164e017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalyst_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('appointment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_alert_appointment_id_appointment'), 'appointment', ['appointment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_alert_catalyst_id_user'), 'user', ['catalyst_id'], ['id'])
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=140), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_alert_catalyst_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_alert_appointment_id_appointment'), type_='foreignkey')
        batch_op.drop_column('appointment_id')
        batch_op.drop_column('catalyst_id')

    # ### end Alembic commands ###
