"""added last_updated_by to Appointment table

Revision ID: a789749f0f61
Revises: 4eab757ee1ee
Create Date: 2025-04-07 17:06:11.890831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a789749f0f61'
down_revision = '4eab757ee1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated_by', sa.Enum('STUDENT', 'TUTOR', name='userrole'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('last_updated_by')

    # ### end Alembic commands ###
