"""Make actual_start_time and actual_end_time nullable

Revision ID: a866432fb942
Revises: 2722172f941d
Create Date: 2025-04-18 04:58:15.808913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a866432fb942'
down_revision = '2722172f941d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('actual_start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('actual_end_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.alter_column('actual_end_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('actual_start_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
