"""initial migrate

Revision ID: b8f42abaa5e7
Revises: 43af2e35dae6
Create Date: 2025-05-08 15:23:18.161061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f42abaa5e7'
down_revision = '43af2e35dae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_work_example_subject_id_subject')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_work_example_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_example'))
    )
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_example_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_example_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_example_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_example_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_example_timestamp'))
        batch_op.drop_index(batch_op.f('ix_work_example_subject_id'))

    op.drop_table('work_example')
    # ### end Alembic commands ###
