"""fixed relationships

Revision ID: bfcc384e91fb
Revises: 1e669aefdfc7
Create Date: 2025-05-08 14:42:25.346968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcc384e91fb'
down_revision = '1e669aefdfc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_work_example_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_example_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_example_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_work_example_subject_id_subject'), 'subject', ['subject_id'], ['id'])
        batch_op.drop_column('upload_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_work_example_subject_id_subject'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_work_example_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_example_timestamp'))
        batch_op.drop_index(batch_op.f('ix_work_example_subject_id'))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('description')
        batch_op.drop_column('title')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
