"""migrate on update

Revision ID: c44fff375e23
Revises: b8f42abaa5e7
Create Date: 2025-05-15 17:44:17.954974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c44fff375e23'
down_revision = 'b8f42abaa5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_other', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('original_filename', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('tutor_upload_agreement', sa.Boolean(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index('ix_work_example_subject_id')
        batch_op.drop_index('ix_work_example_user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.create_index('ix_work_example_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_work_example_subject_id', ['subject_id'], unique=False)
        batch_op.alter_column('subject_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('tutor_upload_agreement')
        batch_op.drop_column('original_filename')
        batch_op.drop_column('subject_other')

    # ### end Alembic commands ###
