"""updated umb-id validation

Revision ID: d86905783178
Revises: 1983771a4835
Create Date: 2025-03-30 21:57:00.404158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86905783178'
down_revision = '1983771a4835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_subject_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_subject_topic'), ['topic'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_umb_id'), ['umb_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_umb_id'), type_='unique')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subject_topic'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_subject_name'), type_='unique')

    # ### end Alembic commands ###
