"""added terms agreement column

Revision ID: e7115838c661
Revises: 512335e477aa
Create Date: 2025-05-09 20:33:01.071497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7115838c661'
down_revision = '512335e477aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_terms_agreement', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.drop_column('upload_terms_agreement')

    # ### end Alembic commands ###
