"""added original filename column

Revision ID: eeb9caaf8d09
Revises: b1feeee3d329
Create Date: 2025-05-09 20:50:38.126053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb9caaf8d09'
down_revision = 'b1feeee3d329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_example', schema=None) as batch_op:
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
