"""added date and time to alert

Revision ID: ffb09534e3f3
Revises: 51783e8cd374
Create Date: 2025-04-14 19:15:05.793035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb09534e3f3'
down_revision = '51783e8cd374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relevant_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('relevant_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_column('relevant_time')
        batch_op.drop_column('relevant_date')

    # ### end Alembic commands ###
